export type Language = "ko" | "en" | "zh" | "es";

export const languageOptions: { value: Language; label: string; short: string }[] = [
  { value: "ko", label: "한국어", short: "KO" },
  { value: "en", label: "English", short: "EN" },
  { value: "zh", label: "中文", short: "中文" },
  { value: "es", label: "Español", short: "ES" },
];

const en: Record<string, string> = {
  "오버뷰":"Overview","오토파일럿":"Autopilot","전략":"Strategies","거래 내역":"Trade history","관심종목":"Watchlist","설정":"Settings","기본 플랜":"Basic plan",
  "2026년 7월 19일 · 장 마감":"July 19, 2026 · Market closed","좋은 저녁이에요, Edward":"Good evening, Edward","Dehua가 시장을 지켜보고 있어요.":"Dehua is watching the market.","종목명 또는 코드 검색":"Search name or ticker","검색 결과가 없어요":"No results found","종목명이나 코드를 다시 확인해 주세요.":"Check the company name or ticker.","오토파일럿 실행 중":"Autopilot active","오토파일럿 시작":"Start autopilot",
  "모의 투자 자산":"Paper portfolio","투자 가능":"Available","투자 중":"Invested","자동 운용 중":"Running automatically","준비 완료":"Ready","승인된 5개 종목의 조건을 실시간으로 확인하고 있어요.":"Monitoring conditions for 5 approved stocks.","설정한 한도 안에서 Dehua가 시장을 관찰하고 모의 거래해요.":"Dehua watches the market and paper-trades within your limits.","오늘 거래":"Trades today","일일 손실 한도":"Daily loss limit","리스크 사용":"Risk used","운용 설정 보기":"View settings",
  "주요 종목":"Popular stocks","간단히 보기 ↑":"Show less ↑","전체보기 →":"View all →","데이터 연결 전 시세 동작 미리보기":"Market preview before live data connection","검색 결과":"results","개":"","신뢰도":"Confidence","자동 주문":"auto order","AI 추천":"AI recommendation","직접 설정":"Manual settings","단기 스윙 전략":"Short-term swing strategy","지지 구간과 거래량 회복 신호를 조합해 Dehua가 계산한 추천안이에요.":"Dehua combines support zones and volume recovery signals to create this plan.","분석 완료":"Analysis complete","다시 분석":"Analyze again","추천 매수가":"Recommended buy","수정 가능":"Editable","AI 기준값을 원하는 가격으로 조정":"Adjust the AI baseline to your preferred price","자동 손절":"Automatic stop","최대 허용 손실 가격":"Maximum permitted loss price","1차 목표가":"First target","자동 익절 목표 가격":"Automatic take-profit target","거래량 회복":"Volume recovery","강함":"Strong","단기 추세":"Short-term trend","상승":"Uptrend","변동성":"Volatility","보통":"Moderate","추천 투자금액":"Recommended amount","직접 조정 가능":"Adjustable","원하는 가격과 투자 금액을 직접 입력하면 해당 조건으로 모의 주문을 실행해요.":"Enter your own prices and amount to run a paper order with those conditions.","투자 금액":"Investment amount","매수 기준가":"Buy price","손절가":"Stop-loss","익절가":"Take-profit","예상 수량":"Estimated quantity","최대 예상 손실":"Maximum loss","손익비":"Risk/reward","전략 시뮬레이션 완료":"Strategy simulation complete","이 전략 시뮬레이션하기":"Simulate this strategy","실제 주문이 아닌 모의 거래입니다. AI 분석은 수익을 보장하지 않습니다.":"Paper trading only. AI analysis does not guarantee returns.",
  "최근 Dehua 활동":"Recent Dehua activity","모든 판단과 실행 과정이 투명하게 기록돼요.":"Every decision and action is recorded transparently.","전체 기록 →":"All activity →","매수":"Buy","보호":"Protect","모의 매수":"paper buy","손절가 조정":"stop-loss adjusted","AI 전략":"AI strategy","지지 구간 진입 및 거래량 반등 확인":"Support entry and volume rebound detected","수익 보호 규칙에 따라 자동 조정":"Automatically adjusted by profit-protection rule","오늘":"Today","주":"shares","원":"KRW","건":"",
  "매수 관찰":"Watch buy","상승 추세":"Uptrend","중립":"Neutral","대기":"Wait","반도체":"Semiconductors","인터넷":"Internet","자동차":"Automotive","2차전지":"Batteries","바이오":"Biotech","금융":"Finance","철강":"Steel","에너지":"Energy","방산":"Defense"
};
const zh: Record<string, string> = {
  "오버뷰":"概览","오토파일럿":"自动驾驶","전략":"策略","거래 내역":"交易记录","관심종목":"自选股","설정":"设置","기본 플랜":"基础方案","2026년 7월 19일 · 장 마감":"2026年7月19日 · 已收盘","좋은 저녁이에요, Edward":"晚上好，Edward","Dehua가 시장을 지켜보고 있어요.":"Dehua 正在关注市场。","종목명 또는 코드 검색":"搜索股票名称或代码","검색 결과가 없어요":"没有搜索结果","종목명이나 코드를 다시 확인해 주세요.":"请检查股票名称或代码。","오토파일럿 실행 중":"自动驾驶运行中","오토파일럿 시작":"启动自动驾驶","모의 투자 자산":"模拟投资资产","투자 가능":"可用资金","투자 중":"投资中","자동 운용 중":"自动运行中","준비 완료":"准备就绪","승인된 5개 종목의 조건을 실시간으로 확인하고 있어요.":"正在实时监控5只已批准股票。","설정한 한도 안에서 Dehua가 시장을 관찰하고 모의 거래해요.":"Dehua 在设定限额内观察市场并模拟交易。","오늘 거래":"今日交易","일일 손실 한도":"每日亏损上限","리스크 사용":"风险使用","운용 설정 보기":"查看运行设置","주요 종목":"热门股票","간단히 보기 ↑":"收起 ↑","전체보기 →":"查看全部 →","데이터 연결 전 시세 동작 미리보기":"实时数据连接前的行情预览","검색 결과":"个结果","개":"","신뢰도":"置信度","자동 주문":"自动订单","AI 추천":"AI 推荐","직접 설정":"手动设置","단기 스윙 전략":"短线波段策略","지지 구간과 거래량 회복 신호를 조합해 Dehua가 계산한 추천안이에요.":"Dehua 结合支撑区与成交量恢复信号生成此方案。","분석 완료":"分析完成","다시 분석":"重新分析","추천 매수가":"建议买入价","수정 가능":"可修改","AI 기준값을 원하는 가격으로 조정":"可将 AI 基准调整为所需价格","자동 손절":"自动止损","최대 허용 손실 가격":"最大允许亏损价格","1차 목표가":"第一目标价","자동 익절 목표 가격":"自动止盈目标价","거래량 회복":"成交量恢复","강함":"强","단기 추세":"短期趋势","상승":"上涨","변동성":"波动性","보통":"中等","추천 투자금액":"建议投资金额","직접 조정 가능":"可自行调整","원하는 가격과 투자 금액을 직접 입력하면 해당 조건으로 모의 주문을 실행해요.":"输入价格和金额后，将按这些条件执行模拟订单。","투자 금액":"投资金额","매수 기준가":"买入价","손절가":"止损价","익절가":"止盈价","예상 수량":"预计数量","최대 예상 손실":"最大预计亏损","손익비":"盈亏比","전략 시뮬레이션 완료":"策略模拟完成","이 전략 시뮬레이션하기":"模拟此策略","실제 주문이 아닌 모의 거래입니다. AI 분석은 수익을 보장하지 않습니다.":"仅为模拟交易。AI 分析不保证收益。","최근 Dehua 활동":"Dehua 最近活动","모든 판단과 실행 과정이 투명하게 기록돼요.":"所有判断和执行过程均透明记录。","전체 기록 →":"全部记录 →","매수":"买入","보호":"保护","모의 매수":"模拟买入","손절가 조정":"调整止损价","AI 전략":"AI 策略","지지 구간 진입 및 거래량 반등 확인":"确认进入支撑区且成交量反弹","수익 보호 규칙에 따라 자동 조정":"根据收益保护规则自动调整","오늘":"今天","주":"股","원":"韩元","건":"笔","매수 관찰":"关注买入","상승 추세":"上涨趋势","중립":"中性","대기":"等待","반도체":"半导体","인터넷":"互联网","자동차":"汽车","2차전지":"动力电池","바이오":"生物科技","금융":"金融","철강":"钢铁","에너지":"能源","방산":"国防"
};
const es: Record<string, string> = {
  "오버뷰":"Resumen","오토파일럿":"Piloto automático","전략":"Estrategias","거래 내역":"Historial","관심종목":"Favoritos","설정":"Configuración","기본 플랜":"Plan básico","2026년 7월 19일 · 장 마감":"19 de julio de 2026 · Mercado cerrado","좋은 저녁이에요, Edward":"Buenas tardes, Edward","Dehua가 시장을 지켜보고 있어요.":"Dehua está vigilando el mercado.","종목명 또는 코드 검색":"Buscar empresa o símbolo","검색 결과가 없어요":"No hay resultados","종목명이나 코드를 다시 확인해 주세요.":"Comprueba el nombre o símbolo.","오토파일럿 실행 중":"Piloto activo","오토파일럿 시작":"Iniciar piloto","모의 투자 자산":"Cartera simulada","투자 가능":"Disponible","투자 중":"Invertido","자동 운용 중":"Operación automática","준비 완료":"Listo","승인된 5개 종목의 조건을 실시간으로 확인하고 있어요.":"Supervisando 5 acciones aprobadas en tiempo real.","설정한 한도 안에서 Dehua가 시장을 관찰하고 모의 거래해요.":"Dehua observa el mercado y simula operaciones dentro de tus límites.","오늘 거래":"Operaciones hoy","일일 손실 한도":"Límite diario","리스크 사용":"Riesgo usado","운용 설정 보기":"Ver configuración","주요 종목":"Acciones principales","간단히 보기 ↑":"Ver menos ↑","전체보기 →":"Ver todo →","데이터 연결 전 시세 동작 미리보기":"Vista previa antes de conectar datos reales","검색 결과":"resultados","개":"","신뢰도":"Confianza","자동 주문":"orden automática","AI 추천":"Recomendación IA","직접 설정":"Configuración manual","단기 스윙 전략":"Estrategia swing a corto plazo","지지 구간과 거래량 회복 신호를 조합해 Dehua가 계산한 추천안이에요.":"Dehua combina zonas de soporte y recuperación de volumen para crear este plan.","분석 완료":"Análisis completo","다시 분석":"Analizar de nuevo","추천 매수가":"Compra recomendada","수정 가능":"Editable","AI 기준값을 원하는 가격으로 조정":"Ajusta el valor base de la IA","자동 손절":"Stop automático","최대 허용 손실 가격":"Precio máximo de pérdida","1차 목표가":"Primer objetivo","자동 익절 목표 가격":"Objetivo de beneficio automático","거래량 회복":"Recuperación de volumen","강함":"Fuerte","단기 추세":"Tendencia corta","상승":"Alcista","변동성":"Volatilidad","보통":"Moderada","추천 투자금액":"Importe recomendado","직접 조정 가능":"Ajustable","원하는 가격과 투자 금액을 직접 입력하면 해당 조건으로 모의 주문을 실행해요.":"Introduce tus precios e importe para simular la orden.","투자 금액":"Importe","매수 기준가":"Precio de compra","손절가":"Stop-loss","익절가":"Take-profit","예상 수량":"Cantidad estimada","최대 예상 손실":"Pérdida máxima","손익비":"Riesgo/beneficio","전략 시뮬레이션 완료":"Simulación completada","이 전략 시뮬레이션하기":"Simular estrategia","실제 주문이 아닌 모의 거래입니다. AI 분석은 수익을 보장하지 않습니다.":"Solo simulación. El análisis de IA no garantiza rentabilidad.","최근 Dehua 활동":"Actividad reciente","모든 판단과 실행 과정이 투명하게 기록돼요.":"Cada decisión y acción queda registrada.","전체 기록 →":"Toda la actividad →","매수":"Compra","보호":"Protección","모의 매수":"compra simulada","손절가 조정":"stop ajustado","AI 전략":"Estrategia IA","지지 구간 진입 및 거래량 반등 확인":"Entrada en soporte y rebote de volumen detectados","수익 보호 규칙에 따라 자동 조정":"Ajuste automático por protección de beneficios","오늘":"Hoy","주":"acciones","원":"KRW","건":"","매수 관찰":"Observar compra","상승 추세":"Tendencia alcista","중립":"Neutral","대기":"Esperar","반도체":"Semiconductores","인터넷":"Internet","자동차":"Automoción","2차전지":"Baterías","바이오":"Biotecnología","금융":"Finanzas","철강":"Acero","에너지":"Energía","방산":"Defensa"
};

const dictionaries: Record<Language, Record<string, string>> = { ko: {}, en, zh, es };
const watchlistCopy: Record<Language, Record<string,string>> = {
  ko: {},
  en: { "저장된 관심종목":"Saved watchlist", "관심종목에 추가":"Add to watchlist", "관심종목에서 삭제":"Remove from watchlist", "관심종목이 비어 있어요":"Your watchlist is empty", "별표 버튼으로 종목을 추가해 보세요.":"Use the star button to save a stock." },
  zh: { "저장된 관심종목":"已保存的自选股", "관심종목에 추가":"添加到自选股", "관심종목에서 삭제":"从自选股删除", "관심종목이 비어 있어요":"自选股为空", "별표 버튼으로 종목을 추가해 보세요.":"点击星标按钮添加股票。" },
  es: { "저장된 관심종목":"Favoritos guardados", "관심종목에 추가":"Añadir a favoritos", "관심종목에서 삭제":"Quitar de favoritos", "관심종목이 비어 있어요":"Tu lista está vacía", "별표 버튼으로 종목을 추가해 보세요.":"Usa la estrella para guardar una acción." },
};
export function tr(language: Language, key: string) { return watchlistCopy[language][key] ?? dictionaries[language][key] ?? key; }
export const localeFor: Record<Language, string> = { ko: "ko-KR", en: "en-US", zh: "zh-CN", es: "es-ES" };
const rangeNames: Record<Language, Record<string, string>> = {
  ko: { "1일":"1일","3일":"3일","1주":"1주","1개월":"1개월","3개월":"3개월","1년":"1년" },
  en: { "1일":"1D","3일":"3D","1주":"1W","1개월":"1M","3개월":"3M","1년":"1Y" },
  zh: { "1일":"1天","3일":"3天","1주":"1周","1개월":"1月","3개월":"3月","1년":"1年" },
  es: { "1일":"1D","3일":"3D","1주":"1S","1개월":"1M","3개월":"3M","1년":"1A" },
};
export function rangeLabel(language: Language, key: string) { return rangeNames[language][key] ?? key; }
